### ISSUE TITLE
[Bug Report]: Error creating WebGL context.

### ISSUE THREAD

**Issue by niraj-khatiwada** [farm-fe/farm#1422]
### Steps to reproduce

- Go to website

### What is actually happening?

Homepage is crashing saying "Error creating WebGL context."
![image](https://github.com/farm-fe/farm/assets/51436631/7fd5ab08-22ea-46dd-9834-dc6a483a62ad)

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 24.84 GB / 31.20 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.9.0 - /run/user/1000/fnm_multishells/72523_1719064431911/bin/node
    Yarn: 1.22.22 - /run/user/1000/fnm_multishells/72523_1719064431911/bin/yarn
    npm: 10.1.0 - /run/user/1000/fnm_multishells/72523_1719064431911/bin/npm
    pnpm: 8.15.4 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.114
    Chromium: 124.0.6367.78
```

**Comment by ErKeLost** [comment]
Can you please provide a error specific link?

**Comment by mks-h** [comment]
This happens on the homepage at https://www.farmfe.org/, when the browser doesn't support (or allow) WebGL. Looking at it from a different browser I can see you have some sort of canvas overlay for the content, which is otherwise rendered from HTML.

**Comment by ErKeLost** [comment]
Yes, the background of the homepage uses canvas. You may need to think about how to solve this problem.

**Comment by mks-h** [comment]
Sorry, but I'm not willing to contribute, atm. My guess is that you could put an error boundary closer to the source of the problem, and ignore any error — so that browsers without WebGL support have a normal white background (or a similar CSS gradient background).

But a better solution might be to use CSS to achieve a similar gradient background, without any need for WebGL. As for the snow dots... There may be a way to have them, too, although they won't be random.

**Comment by mks-h** [comment]
No problem! Nothing wrong with your reply either way.

**Comment by ErKeLost** [comment]
We will consider this issue later. i will close this issue first.
