### ISSUE TITLE
[Bug Report]: Error on creating a project with PascalCase naming

### ISSUE THREAD

**Issue by n-ce** [farm-fe/farm#1728]
### Steps to reproduce

1. npm create farm@latest
2. Enter Project Name..... Pascal

### What is actually happening?

![Screenshot_20240822-130157_1](https://github.com/user-attachments/assets/1450128c-e9bc-4791-b923-6fbb5618af79)

Vite on the other hand converts the PascalCase to lower case without producing an error.

### System Info

```Shell
System:
    OS: android
    CPU: Unknown
    Memory: 1.37 GB / 3.66 GB
  Binaries:
    Node: 22.5.1 - /data/data/com.termux/files/usr/bin/node
    Yarn: 1.22.22 - /data/data/com.termux/files/usr/bin/yarn
    npm: 10.8.2 - /data/data/com.termux/files/usr/bin/npm
    pnpm: 9.6.0 - /data/data/com.termux/files/usr/bin/pnpm
```

**Comment by fu050409** [comment]
Hi there, the prompting project name is used for nodejs/rust project name, lower case is required. I'll optimize the prompt logic later to ask again when the input name is invalid.

**Comment by ErKeLost** [comment]
@fu050409  If the uses upper case, we can help convert it to lower case. Isn't this better?

**Comment by fu050409** [comment]
@ErKeLost I don't think so since we shouldn't have to make the decisions for the user. If we simply follow some logic that converts a user-entered project name containing uppercase letters to lowercase, this may not necessarily what the user expects. For example, the user entered `MyProject`, we won't know whether `my-project` or `myproject` is expected. If our logic is the previous, and there's a directory `my-project` exists in the current directory, this will also cause unexpected security issues. Users may cost more time to remove and recreate a new project than retype a project name. So I think just decline the input and prompt again to ask for a valid project name.

**Comment by ErKeLost** [comment]
The normal logic is

**Comment by wre232114** [comment]
> @ErKeLost I don't think so since we shouldn't have to make the decisions for the user. If we simply follow some logic that converts a user-entered project name containing uppercase letters to lowercase, this may not necessarily what the user expects. For example, the user entered `MyProject`, we won't know whether `my-project` or `myproject` is expected. If our logic is the previous, and there's a directory `my-project` exists in the current directory, this will also cause unexpected security issues. Users may cost more time to remove and recreate a new project than retype a project name. So I think just decline the input and prompt again to ask for a valid project name.

I think both ways are fine. We can just prevent CamelCase name for now
